version: "3"
services:
  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
     - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
     - 9090:9090
    depends_on:
     - node-exporter

  node-exporter:
    image: prom/node-exporter:latest
    ports:
     - 9100

  grafana:
    image: grafana/grafana
    environment:
      - GF_USERS_DEFAULT_THEME=light
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./config/grafana/datasources/prometheus.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
      - ./config/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/all.yml
    ports:
     - 3000:3000
    depends_on:
      - prometheus